services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AgrosupDijon\BulmaPackage\:
    resource: '../Classes/*'

  AgrosupDijon\BulmaPackage\ViewHelpers\WebsiteSettings\MainLogoViewHelper:
    public: true
