services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AgrosupDijon\BulmaPackage\:
    resource: '../Classes/*'

  AgrosupDijon\BulmaPackage\ViewHelpers\WebsiteSettings\MainLogoViewHelper:
    public: true

  AgrosupDijon\BulmaPackage\Hooks\PageRenderer\BulmaMetaTagHook:
    public: true

  AgrosupDijon\BulmaPackage\Hooks\PageRenderer\BulmaPageTitleHook:
    public: true

  AgrosupDijon\BulmaPackage\Hooks\PageRenderer\PreProcessHook:
    public: true
